version: '3.7'

services:

  mysqlsrv:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Ws2022!"
      MYSQL_DATABASE: "p2as_db"
    networks:
      - p2as-network
      
  namingserver:
    image: wlngtn/p2as-naming-server:220711
    ports:
      - "8761:8761"
    depends_on:
      - mysqlsrv
    networks:
      - p2as-network
 
  apigateway:
    image: wlngtn/p2as-api-gateway:230226
    ports:
      - "8765:8765"
    depends_on:
      - namingserver
      - mysqlsrv
    networks:
      - p2as-network
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://namingserver:8761/eureka
  
  apiCliente:
   image: wlngtn/p2as-api:230226
   ports:
     - "8086:8080"  
   depends_on:
     - apigateway
     - namingserver
     - mysqlsrv
   networks:
     - p2as-network
   environment:
     EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://namingserver:8761/eureka
     SPRING.DATASOURCE.URL: jdbc:mysql://mysqlsrv:3306/p2as_db?createDatabaseIfNotExist=true&serverTimezone=UTC
     SPRING.APPLICATION.NAME: CLIENTE-SERVICE
     SERVER.PORT: 8086
   build:
     context: ./
     dockerfile: Dockerfile
   restart: unless-stopped
   healthcheck:
     test: curl --fail http://localhost:8765/p2as-api/v1/api/clientes || exit 1
     interval: 60s
     retries: 5
     start_period: 20s
     timeout: 10s
     
  apiProfissional:
   image: wlngtn/p2as-api:230226
   ports:
     - "8082:8080"  
   depends_on:
     - apiCliente
     - apigateway
     - namingserver
     - mysqlsrv
   networks:
     - p2as-network
   environment:
     EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://namingserver:8761/eureka
     SPRING.DATASOURCE.URL: jdbc:mysql://mysqlsrv:3306/p2as_db?createDatabaseIfNotExist=true&serverTimezone=UTC
     SPRING.APPLICATION.NAME: PROFISSIONAL-SERVICE
     SERVER.PORT: 8082
   healthcheck:
     test: curl --fail http://localhost:8765/p2as-api/v1/api/profissionais || exit 1
     interval: 60s
     retries: 5
     start_period: 20s
     timeout: 10s   
     
  apiServico:
   image: wlngtn/p2as-api:230226
   ports:
     - "8083:8080"  
   depends_on:
     - apigateway
     - namingserver
     - mysqlsrv
   networks:
     - p2as-network
   environment:
     EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://namingserver:8761/eureka
     SPRING.DATASOURCE.URL: jdbc:mysql://mysqlsrv:3306/p2as_db?createDatabaseIfNotExist=true&serverTimezone=UTC
     SPRING.APPLICATION.NAME: SERVICOS-SERVICE
     SERVER.PORT: 8083
   build:
     context: ./
     dockerfile: Dockerfile
   restart: unless-stopped
   healthcheck:
     test: curl --fail http://localhost:8765/p2as-api/v1/api/clientes || exit 1
     interval: 60s
     retries: 5
     start_period: 20s
     timeout: 10s
     
  apiLocalizacao:
   image: wlngtn/p2as-api:230226
   ports:
     - "8084:8080"  
   depends_on:
     - apigateway
     - namingserver
     - mysqlsrv
   networks:
     - p2as-network
   environment:
     EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://namingserver:8761/eureka
     SPRING.DATASOURCE.URL: jdbc:mysql://mysqlsrv:3306/p2as_db?createDatabaseIfNotExist=true&serverTimezone=UTC
     SPRING.APPLICATION.NAME: LOCALIZACAO-SERVICE
     SERVER.PORT: 8084
   build:
     context: ./
     dockerfile: Dockerfile
   restart: unless-stopped
   healthcheck:
     test: curl --fail http://localhost:8765/p2as-api/v1/api/clientes || exit 1
     interval: 60s
     retries: 5
     start_period: 20s
     timeout: 10s
  
  apiResiliencia:
   image: wlngtn/p2as-api:230226
   ports:
     - "8085:8080"  
   depends_on:
     - apigateway
     - namingserver
     - mysqlsrv
   networks:
     - p2as-network
   environment:
     EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://namingserver:8761/eureka
     SPRING.DATASOURCE.URL: jdbc:mysql://mysqlsrv:3306/p2as_db?createDatabaseIfNotExist=true&serverTimezone=UTC
     SPRING.APPLICATION.NAME: RESILIENCE-SERVICE
     SERVER.PORT: 8085
   build:
     context: ./
     dockerfile: Dockerfile
   restart: unless-stopped
   healthcheck:
     test: curl --fail http://localhost:8765/p2as-api/v1/api/clientes || exit 1
     interval: 60s
     retries: 5
     start_period: 20s
     timeout: 10s
    
     
  p2asFront:
    image: wlngtn/p2as-front:latest
    ports:
      - "80:80"  
    depends_on:
      - apiCliente
      - apigateway
      - namingserver
      - mysqlsrv
    networks:
      - p2as-network

networks: 
  p2as-network:
    driver: bridge