version: '3'

services:

  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "Ws2022!"
      MYSQL_DATABASE: "p2as_db"
    ports:
      - "3307:3306"
    volumes:
      - /home/renatogroffe/Desenvolvimento/Docker/Volumes/MySql:/var/lib/mysql
    networks:
      - p2as-network

  naming-server:
    image: wlngtn/p2as-naming-server:220711
    ports:
      - "8761:8761"
    networks:
      - p2as-network

  api:
    image: wlngtn/p2as-api:220711
    ports:
      - "8080:8080"
    networks:
      - p2as-network
    deploy:
      mode: global
    depends_on:
      - mysqlsrv  
      
networks: 
  p2as-network:
    driver: bridge
      
   