version: '3'

services:

  mysqlsrv:
    image: mysql:5.7
    ports:
        - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Ws2022!"
      MYSQL_DATABASE: "p2as_db"
    networks:
      - p2as-network

  namingserver:
    image: wlngtn/p2as-naming-server:220711
    ports:
      - "8761:8761"
    depends_on:
      - mysqlsrv
    networks:
      - p2as-network
 
  apigateway:
    image: wlngtn/p2as-api-gateway:220711
    ports:
      - "8765:8765"
    depends_on:
      - namingserver
      - mysqlsrv
    networks:
      - p2as-network
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://namingserver:8761/eureka
 
  apiCliente:
    image: wlngtn/p2as-api:220711
    ports:
      - "8080:8080"  
    depends_on:
      - apigateway
      - namingserver
      - mysqlsrv
    networks:
      - p2as-network
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://namingserver:8761/eureka
      SPRING.DATASOUCE.URL: jdbc:mysql://mysqlsrv:3306/p2as_db?createDatabaseIfNotExist=true&serverTimezone=UTC
          
networks: 
  p2as-network:
    driver: bridge