version: '3'

services:

  mysqlsrv:
    image: mysql:5.7
    ports:
        - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Ws2022!"
      MYSQL_DATABASE: "p2as_db"
    networks:
      - p2as-network
    
  namingserver:
    image: wlngtn/p2as-naming-server:220711
    ports:
      - "8761:8761"
    depends_on:
      - mysqlsrv
    networks:
      - p2as-network

  api:
    image: wlngtn/p2as-api:220711
    ports:
      - "8080:8080"  
    depends_on:
      - namingserver
      - mysqlsrv
    networks:
      - p2as-network
          
networks: 
  p2as-network:
    driver: bridge